[build]
  command = "bun install && bun run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  BUN_VERSION = "1.0.0"
  NETLIFY_USE_BUN = "true"
